Repository nbcamp-archive/alarm-ios, pull requests merged in 2023-10, with the labels that each got.

#18 Feat/add-weather-view
  Alarm.xcodeproj/project.pbxproj
  Alarm/Presentation/Weather/UIcolor+CALayer.swift
  Alarm/Presentation/Weather/WeatherViewController.swift
  Alarm/Presentation/Weather/detailInfoView.swift
  Alarm/Presentation/Weather/weatherAPI.swift
  Alarm/Resource/Assets.xcassets/weatherIcon/Contents.json
  Alarm/Resource/Assets.xcassets/weatherIcon/cludy.imageset/Contents.json
  Alarm/Resource/Assets.xcassets/weatherIcon/cludy.imageset/cludy.png
  Alarm/Resource/Assets.xcassets/weatherIcon/degreeSign.imageset/Contents.json
  Alarm/Resource/Assets.xcassets/weatherIcon/degreeSign.imageset/degree-sign.png
  Alarm/Resource/Assets.xcassets/weatherIcon/humidity.imageset/Contents.json
  Alarm/Resource/Assets.xcassets/weatherIcon/humidity.imageset/icon (3).png
  Alarm/Resource/Assets.xcassets/weatherIcon/wind.imageset/Contents.json
  Alarm/Resource/Assets.xcassets/weatherIcon/wind.imageset/wind.png
  Alarm/Resource/Base.lproj/LaunchScreen.storyboard
Labels: enhancement, design

#20 Feat/alarm
  Alarm/Presentation/Alarm/AlarmViewController.swift
Labels: enhancement, design

#21 Feat/stopwatch
  Alarm.xcodeproj/project.pbxproj
  Alarm/Application/MainTabBarCoordinator.swift
  Alarm/Global/Extension/UIButton+Extension.swift
  Alarm/Global/Extension/UIView+Extension.swift
  Alarm/Presentation/Stopwatch/StopWatch.swift
  Alarm/Presentation/Stopwatch/StopWatchPage.storyboard
  Alarm/Presentation/Stopwatch/StopwatchViewController.swift
  Alarm/Presentation/Stopwatch/StopwatchViewCoordinator.swift
  Alarm/Resource/Assets.xcassets/StopWatchColorSet/Contents.json
  Alarm/Resource/Assets.xcassets/StopWatchColorSet/StartBackground.colorset/Contents.json
  Alarm/Resource/Assets.xcassets/StopWatchColorSet/StartText.colorset/Contents.json
  Alarm/Resource/Assets.xcassets/StopWatchColorSet/StopBackground.colorset/Contents.json
  Alarm/Resource/Assets.xcassets/StopWatchColorSet/StopText.colorset/Contents.json
Labels: enhancement, design

#22 Feat/timer
  Alarm.xcodeproj/project.pbxproj
  Alarm/Presentation/Timer/SelectRingtoneTableViewController.swift
  Alarm/Presentation/Timer/TimerModel.swift
  Alarm/Presentation/Timer/TimerPage.storyboard
  Alarm/Presentation/Timer/TimerViewController.swift
  Alarm/Presentation/Timer/TimerViewCoordinator.swift
Labels: enhancement, design

#26 Feat/alarm
  Alarm.xcodeproj/project.pbxproj
  Alarm/Presentation/Alarm/AddAlarm/AddAlarmViewController.swift
  Alarm/Presentation/Alarm/AddAlarm/RepeatViewController.swift
  Alarm/Presentation/Alarm/AddAlarm/SoundViewController.swift
  Alarm/Presentation/Alarm/AlarmModel.swift
  Alarm/Presentation/Alarm/AlarmViewController.swift
Labels: maintanance

#29 Feat/timer
  Alarm.xcodeproj/project.pbxproj
  Alarm/Application/AppDelegate.swift
  Alarm/Presentation/Timer/CircularSliderView.swift
  Alarm/Presentation/Timer/TimerModel.swift
  Alarm/Presentation/Timer/TimerPage.storyboard
  Alarm/Presentation/Timer/TimerViewController.swift
Labels: enhancement, design

#31 feat: 스탑워치 아날로그 페이스 구현
  Alarm/Presentation/Stopwatch/StopWatch.swift
  Alarm/Presentation/Stopwatch/StopWatchPage.storyboard
  Alarm/Presentation/Stopwatch/StopwatchViewController.swift
  Alarm/Resource/Assets.xcassets/analogStopwatch.imageset/Contents.json
  Alarm/Resource/Assets.xcassets/analogStopwatch.imageset/Group 702x.png
  Alarm/Resource/Assets.xcassets/analogStopwatch.imageset/Group 703x.png
Labels: enhancement, design

#35 Fix/alarm view
  Alarm/Presentation/Alarm/AlarmViewController.swift
  Alarm/Utility/UserDefaultsManager.swift
Labels: bug

#39 remove force unwrapping & HEX initialize
  Alarm/Presentation/Alarm/AlarmViewController.swift
  Alarm/Presentation/Stopwatch/StopWatchViewController.swift
  Alarm/Presentation/Timer/TimerViewController.swift
  Alarm/Presentation/Weather/WeatherViewController.swift
  Alarm/Presentation/Weather/weatherCondition.swift
Labels: bug

#40 Develop
  Alarm.xcodeproj/project.pbxproj
  Alarm/Presentation/Alarm/AlarmViewController.swift
  Alarm/Presentation/Stopwatch/StopWatchViewController.swift
  Alarm/Presentation/Stopwatch/StopwatchViewController.swift
  Alarm/Presentation/Timer/TimerViewController.swift
  Alarm/Presentation/Weather/CAAnimationGradientLayer.swift
  Alarm/Presentation/Weather/WeatherViewController.swift
  Alarm/Presentation/Weather/weatherCondition.swift
  Alarm/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Alarm/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/100.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/102.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/1024.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/114.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/120.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/128.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/144.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/152.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/16.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/167.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/172.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/180.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/196.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/20.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/216.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/256.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/29.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/32.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/40.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/48.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/50.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/512.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/55.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/57.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/58.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/60.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/64.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/66.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/72.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/76.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/80.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/87.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/88.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/92.png
  Alarm/Resource/Assets.xcassets/Assets/AppIcon.appiconset/Contents.json
  Alarm/Resource/Assets.xcassets/Assets/Contents.json
Labels: bug, maintanance

#42 Develop
  Alarm/Presentation/Alarm/AddAlarm/AddAlarmViewController.swift
  Alarm/Presentation/Alarm/AlarmViewController.swift
  Alarm/Presentation/Weather/WeatherViewController.swift
  Alarm/Presentation/Weather/detailInfoView.swift
  Alarm/Presentation/Weather/weatherCondition.swift
Labels: bug, maintanance
